title: Jerome Rasky
description: Personal Website
author: Jerome Rasky
logo: /static/img/avatar.jpg
github: https://github.com/jrasky
about: Software Engineer
source: src
destination: src/_site

baseurl: ""
url: "http://rasky.co/"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules"
  - "tasks"

include:
  - ".nojekyll"

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]

highlighter: rouge

host: 0.0.0.0
port: 4000
